/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 06-Jan-2017 13:26:34 					*/
/*  DBMS       : SQL Server 2012 						*/
/*	Author	   : Kirill Markov							*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Client_Client_Type]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Client] DROP CONSTRAINT [FK_Client_Client_Type]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Client_Address_Address]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Client_Address] DROP CONSTRAINT [FK_Client_Address_Address]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Client_Address_Client]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Client_Address] DROP CONSTRAINT [FK_Client_Address_Client]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Client_Email_Client]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Client_Email] DROP CONSTRAINT [FK_Client_Email_Client]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Client_Email_E-mail]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Client_Email] DROP CONSTRAINT [FK_Client_Email_E-mail]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Client_Phone_Client]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Client_Phone] DROP CONSTRAINT [FK_Client_Phone_Client]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Client_Phone_Phone]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Client_Phone] DROP CONSTRAINT [FK_Client_Phone_Phone]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_E-mail_Notification_Notificztion_Task]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [E-mail_Notification] DROP CONSTRAINT [FK_E-mail_Notification_Notificztion_Task]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_E-mail_Notification_Project]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [E-mail_Notification] DROP CONSTRAINT [FK_E-mail_Notification_Project]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Notificztion_Task_Notification_Event]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Notificztion_Task] DROP CONSTRAINT [FK_Notificztion_Task_Notification_Event]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Product_License_Client]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Product_License] DROP CONSTRAINT [FK_Product_License_Client]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Product_License_License_Type]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Product_License] DROP CONSTRAINT [FK_Product_License_License_Type]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Product_License_Project]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Product_License] DROP CONSTRAINT [FK_Product_License_Project]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Project_Role_User]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Project_Role] DROP CONSTRAINT [FK_Project_Role_User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Project_Role_Access_Function_Project_Access_Function]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Project_Role_Access_Function] DROP CONSTRAINT [FK_Project_Role_Access_Function_Project_Access_Function]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Project_Role_Access_Function_Project_Role]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Project_Role_Access_Function] DROP CONSTRAINT [FK_Project_Role_Access_Function_Project_Role]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Support_Entitlement_Client]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Support_Entitlement] DROP CONSTRAINT [FK_Support_Entitlement_Client]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Support_Entitlement_Project]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Support_Entitlement] DROP CONSTRAINT [FK_Support_Entitlement_Project]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_And_His_Role_Global_User_Role]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User_And_His_Role] DROP CONSTRAINT [FK_User_And_His_Role_Global_User_Role]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_And_His_Role_User]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User_And_His_Role] DROP CONSTRAINT [FK_User_And_His_Role_User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_Invitation_User]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User_Invitation] DROP CONSTRAINT [FK_User_Invitation_User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_Project_Project]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User_Project] DROP CONSTRAINT [FK_User_Project_Project]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_Project_Project_Role]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User_Project] DROP CONSTRAINT [FK_User_Project_Project_Role]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_Project_User]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User_Project] DROP CONSTRAINT [FK_User_Project_User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_Role_Access_Function_Access_Function]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User_Role_Access_Function] DROP CONSTRAINT [FK_User_Role_Access_Function_Access_Function]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_User_Role_Access_Function_User_Role]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [User_Role_Access_Function] DROP CONSTRAINT [FK_User_Role_Access_Function_User_Role]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Access_Function]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Access_Function]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Address]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Address]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Client]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Client]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Client_Address]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Client_Address]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Client_Email]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Client_Email]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Client_Phone]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Client_Phone]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Client_Type]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Client_Type]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[E-mail]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [E-mail]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[E-mail_Notification]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [E-mail_Notification]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Global_User_Role]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Global_User_Role]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Invitation_User_Settings]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Invitation_User_Settings]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[LDAP_Settings]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [LDAP_Settings]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[License_Type]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [License_Type]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Notification_Event]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Notification_Event]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Notification_Morpheme]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Notification_Morpheme]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Notificztion_Task]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Notificztion_Task]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Phone]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Phone]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Product_License]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Product_License]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Project]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Project]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Project_Access_Function]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Project_Access_Function]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Project_Role]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Project_Role]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Project_Role_Access_Function]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Project_Role_Access_Function]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Support_Entitlement]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Support_Entitlement]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[User]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [User]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[User_And_His_Role]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [User_And_His_Role]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[User_Invitation]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [User_Invitation]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[User_Project]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [User_Project]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[User_Role_Access_Function]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [User_Role_Access_Function]
GO

/* Create Tables */

CREATE TABLE [Access_Function]
(
	[ID_Access_Function] numeric(18) NOT NULL,
	[Function_Name] nvarchar(255) NOT NULL    -- Название функции, к которой предоставляется доступ
)
GO

CREATE TABLE [Address]
(
	[ID_Address] numeric(18) NOT NULL,
	[Address_Row] varchar(50) NOT NULL,
	[ID_Client] numeric(18) NULL
)
GO

CREATE TABLE [Client]
(
	[ID_Client] numeric(18) NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(450) NOT NULL,    -- Название клиента
	[INN] nvarchar(50) NULL,
	[OGRN] nvarchar(50) NULL,
	[KPP] nvarchar(50) NULL,
	[ID_Client_Type] numeric(18) NOT NULL,
	[Inner_Name] nvarchar(255) NULL,    -- Внутреннее название клиента (между собой)
	[ID_Address] numeric(18) NULL
)
GO

CREATE TABLE [Client_Address]
(
	[ID_Client] numeric(18) NOT NULL,
	[ID_Address] numeric(18) NOT NULL
)
GO

CREATE TABLE [Client_Email]
(
	[ID_Client] numeric(18) NOT NULL,
	[ID_E-mail] numeric(18) NOT NULL
)
GO

CREATE TABLE [Client_Phone]
(
	[ID_Client] numeric(18) NOT NULL,
	[ID_Phone] numeric(18) NOT NULL
)
GO

CREATE TABLE [Client_Type]
(
	[ID_Client_Type] numeric(18) NOT NULL,
	[Type_Name] nvarchar(255) NOT NULL    -- Название типа клиента
)
GO

CREATE TABLE [E-mail]
(
	[ID_E-mail] numeric(18) NOT NULL,
	[Address] nvarchar(255) NOT NULL    -- Ажрес почтового ящика
)
GO

CREATE TABLE [E-mail_Notification]
(
	[ID_E-mail_Notification] numeric(18) NOT NULL,
	[ID_User_To_Notificate] numeric(18) NOT NULL,    -- Идентификатор пользователя, для которого будет прилетать оповещение
	[ID_Project] numeric(18) NOT NULL,    -- Идентификатор проекта, по которому должно прилетать оповещение.
	[ID_Notificztion_Task] numeric(18) NOT NULL
)
GO

CREATE TABLE [Global_User_Role]
(
	[ID_User_Role] numeric(18) NOT NULL,
	[Name] nvarchar(255) NOT NULL    -- Название роли
)
GO

CREATE TABLE [Invitation_User_Settings]
(
	[ID_Invitation_User_Settings] numeric(18) NOT NULL IDENTITY (1, 1),
	[Count_Invitations_Per_Day] numeric(18) NOT NULL DEFAULT 10,    -- Количество приглашений, которые пользователь может отправить за 1 день.
	[Invitation_E-mail] nvarchar(255) NOT NULL    -- Почтовый ящик, с которого будут отправляться приглашения на присоединение
)
GO

CREATE TABLE [LDAP_Settings]
(
	[ID_LDAP_Settings] numeric(18) NOT NULL IDENTITY (1, 1),
	[Domain_Components] nvarchar(255) NOT NULL,    -- Список domain component
	[Organizational_Unit] varbinary(255) NOT NULL    -- Список organizational unit
)
GO

CREATE TABLE [License_Type]
(
	[ID_License_Type] numeric(18) NOT NULL IDENTITY (1, 1),
	[Type_Name] nvarchar(255) NOT NULL    -- Название типа лицензии
)
GO

CREATE TABLE [Notification_Event]
(
	[ID_Notification_Event] numeric(18) NOT NULL,
	[Event_Type] varchar(50) NOT NULL    -- Тип события - жёстко задан в системе:  	1. Завершение периода ТП по проекту 	2. Завершение лицензии по проекту.
)
GO

CREATE TABLE [Notification_Morpheme]
(
	[ID_Notification_Morpheme] numeric(18) NOT NULL,
	[Template] nvarchar(50) NOT NULL,    -- Сама морфема
	[Description] nvarchar(500) NULL    -- Описание морфемы
)
GO

CREATE TABLE [Notificztion_Task]
(
	[ID_Notificztion_Task] numeric(18) NOT NULL,
	[Notification_Before_Month] numeric(18) NULL,    -- Количество месяцев до
	[Notification_Before_Week] numeric(18) NULL,
	[Notification_Before_Day] numeric(18) NULL,
	[Notification_Before_Hour] numeric(18) NULL,
	[Notification_Text] nvarchar(max) NOT NULL,    -- Текст оповещения, включая различные морфемы параметров.
	[ID_Notification_Event] numeric(18) NOT NULL,    -- Идентификатор события, относительно которого должно отправляться оповещение
	[Name] nvarchar(255) NOT NULL    -- Название задачи оповещения
)
GO

CREATE TABLE [Phone]
(
	[ID_Phone] numeric(18) NOT NULL,
	[Phone_Row] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [Product_License]
(
	[ID_Product_License] numeric(18) NOT NULL IDENTITY (1, 1),
	[ID_Project] numeric(18) NOT NULL,    -- Проект, на которую выдана лицензия
	[ID_Client] numeric(18) NOT NULL,    -- Клиент, которму выдана лицензия
	[Date_Begin] datetime2(7) NOT NULL,    -- Дата выдачи лицензии
	[Date_End] datetime2(7) NOT NULL,    -- Дата окончания лицензии
	[ID_License_Type] numeric(18) NOT NULL,    -- Тип лицензии, которая была передана клиенту
	[License_Count] numeric(18) NOT NULL,    -- Количество выданных лицензий
	[Details] nvarchar(max) NULL    -- Детали по лицензии, номер договора...
)
GO

CREATE TABLE [Project]
(
	[ID_Project] numeric(18) NOT NULL IDENTITY(1,1),
	[Name] nvarchar(255) NOT NULL,    -- Название проекта (по этому полю идёт полнотекстовый поиск).
	[Date_Create] datetime2(7) NOT NULL,    -- Дата создания проекта.
	[Description] nvarchar(512) NULL -- Описание проекта.
)
GO

CREATE TABLE [Project_Access_Function]
(
	[ID_Role_Access_Function] numeric(18) NOT NULL,    -- ID
	[Name] nvarchar(255) NULL    -- Название функции
)
GO

CREATE TABLE [Project_Role]
(
	[ID_Project_Role] numeric(18) NOT NULL,
	[Role_Name] nvarchar(255) NOT NULL,
	[Is_Admin] bit NOT NULL DEFAULT 0,    -- Флаг показывает является ли данная роль администратором. Эта роль создаётся автоматически и не может быть удалена.
)
GO

CREATE TABLE [Project_Role_Access_Function]
(
	[ID_Project_Role] numeric(18) NOT NULL,
	[ID_Role_Access_Function] numeric(18) NOT NULL
)
GO

CREATE TABLE [Support_Entitlement]
(
	[ID_Support_Entitlement] numeric(18) NOT NULL IDENTITY (1, 1),
	[ID_Project] numeric(18) NOT NULL,
	[ID_Client] numeric(18) NOT NULL,
	[Date_Begin] datetime2(7) NOT NULL,
	[Date_End] datetime2(7) NOT NULL,
	[Note] nvarchar(max) NULL    -- Заметки по работе ТП
)
GO

CREATE TABLE [User]
(
	[ID_User] numeric(18) NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(255) NULL,    -- Имя пользователя
	[Surname] nvarchar(255) NULL,
	[Password] nvarchar(255) NULL,    -- Хеш пароля пользователя
	[Is_Ldap_User] bit NOT NULL DEFAULT 0,    -- Является ли пользователь LDAP пользователем
	[E-mail] nvarchar(255) NOT NULL,    -- Почтовый ящик пользователя
	[Date_Creation] datetime2(7) NOT NULL,
	[Login] nvarchar(255) NOT NULL    -- User login or nickname
)
GO

CREATE TABLE [User_And_His_Role]
(
	[ID_User] numeric(18) NOT NULL,
	[ID_User_Role] numeric(18) NOT NULL
)
GO

CREATE TABLE [User_Invitation]
(
	[ID_User_Invitation] numeric(18) NOT NULL IDENTITY (1, 1),
	[E-mail] nvarchar(255) NOT NULL,
	[Date_Of_Invitation] datetime2(7) NOT NULL,    -- Дата, когда было отправлено приглашение
	[ID_User_Referrer] numeric(18) NOT NULL,    -- Пользователь, который пригласил.
	[IsAccepted] bit NOT NULL DEFAULT 0    -- Принял ли новый пользователь приглашение. Если да, то на указанные e-mail больше нельзя отправить приглашения.
)
GO

CREATE TABLE [User_Project]
(
	[ID_User] numeric(18) NOT NULL,
	[ID_Project] numeric(18) NOT NULL,
	[ID_Project_Role] numeric(18) NOT NULL    -- Роль, которая была назначена пользователю в конкретном проекте
)
GO

CREATE TABLE [User_Role_Access_Function]
(
	[ID_User_Role] numeric(18) NOT NULL,
	[ID_Access_Function] numeric(18) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Access_Function] 
 ADD CONSTRAINT [PK_AccessFunctions]
	PRIMARY KEY CLUSTERED ([ID_Access_Function] ASC)
GO

ALTER TABLE [Access_Function] 
 ADD CONSTRAINT [UK_Access_Function_Name] UNIQUE NONCLUSTERED ([Function_Name] ASC)
GO

ALTER TABLE [Address] 
 ADD CONSTRAINT [PK_Address]
	PRIMARY KEY CLUSTERED ([ID_Address] ASC)
GO

ALTER TABLE [Address] 
 ADD CONSTRAINT [UK_Address_Address_Row] UNIQUE NONCLUSTERED ([Address_Row] ASC)
GO

ALTER TABLE [Client] 
 ADD CONSTRAINT [PK_Client]
	PRIMARY KEY CLUSTERED ([ID_Client] ASC)
GO

ALTER TABLE [Client] 
 ADD CONSTRAINT [UK_Client_Name] UNIQUE NONCLUSTERED ([Name] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Client_Client_Type] 
 ON [Client] ([ID_Client_Type] ASC)
GO

ALTER TABLE [Client_Address] 
 ADD CONSTRAINT [PK_Client_Address]
	PRIMARY KEY CLUSTERED ([ID_Address] ASC,[ID_Client] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Client_Address_Address] 
 ON [Client_Address] ([ID_Address] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Client_Address_Client] 
 ON [Client_Address] ([ID_Client] ASC)
GO

ALTER TABLE [Client_Email] 
 ADD CONSTRAINT [PK_Client_Email]
	PRIMARY KEY CLUSTERED ([ID_Client] ASC,[ID_E-mail] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Client_Email_Client] 
 ON [Client_Email] ([ID_Client] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Client_Email_E-mail] 
 ON [Client_Email] ([ID_E-mail] ASC)
GO

ALTER TABLE [Client_Phone] 
 ADD CONSTRAINT [PK_Client_Phone]
	PRIMARY KEY CLUSTERED ([ID_Client] ASC,[ID_Phone] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Client_Phone_Client] 
 ON [Client_Phone] ([ID_Client] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Client_Phone_Phone] 
 ON [Client_Phone] ([ID_Phone] ASC)
GO

ALTER TABLE [Client_Type] 
 ADD CONSTRAINT [PK_Client_Type]
	PRIMARY KEY CLUSTERED ([ID_Client_Type] ASC)
GO

ALTER TABLE [Client_Type] 
 ADD CONSTRAINT [UK_Client_Type_Name] UNIQUE NONCLUSTERED ([Type_Name] ASC)
GO

ALTER TABLE [E-mail] 
 ADD CONSTRAINT [PK_E-mail]
	PRIMARY KEY CLUSTERED ([ID_E-mail] ASC)
GO

ALTER TABLE [E-mail] 
 ADD CONSTRAINT [UK_E-mail_Address] UNIQUE NONCLUSTERED ([Address] ASC)
GO

ALTER TABLE [E-mail_Notification] 
 ADD CONSTRAINT [PK_E-mail_Notification]
	PRIMARY KEY CLUSTERED ([ID_E-mail_Notification] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_E-mail_Notification_Notificztion_Task] 
 ON [E-mail_Notification] ([ID_Notificztion_Task] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_E-mail_Notification_Project] 
 ON [E-mail_Notification] ([ID_Project] ASC)
GO

ALTER TABLE [Global_User_Role] 
 ADD CONSTRAINT [PK_User_Role]
	PRIMARY KEY CLUSTERED ([ID_User_Role] ASC)
GO

ALTER TABLE [Global_User_Role] 
 ADD CONSTRAINT [UK_User_Role_Name] UNIQUE NONCLUSTERED ([Name] ASC)
GO

ALTER TABLE [Invitation_User_Settings] 
 ADD CONSTRAINT [PK_Invitation_User_Settings]
	PRIMARY KEY CLUSTERED ([ID_Invitation_User_Settings] ASC)
GO

ALTER TABLE [LDAP_Settings] 
 ADD CONSTRAINT [PK_LDAP_Settings]
	PRIMARY KEY CLUSTERED ([ID_LDAP_Settings] ASC)
GO

ALTER TABLE [License_Type] 
 ADD CONSTRAINT [PK_License_Type]
	PRIMARY KEY CLUSTERED ([ID_License_Type] ASC)
GO

ALTER TABLE [License_Type] 
 ADD CONSTRAINT [UK_License_Type_Name] UNIQUE NONCLUSTERED ([Type_Name] ASC)
GO

ALTER TABLE [Notification_Event] 
 ADD CONSTRAINT [PK_Notification_Event]
	PRIMARY KEY CLUSTERED ([ID_Notification_Event] ASC)
GO

ALTER TABLE [Notification_Event] 
 ADD CONSTRAINT [UK_Notification_Event_Type] UNIQUE NONCLUSTERED ([Event_Type] ASC)
GO

ALTER TABLE [Notification_Morpheme] 
 ADD CONSTRAINT [PK_Notification_Morpheme]
	PRIMARY KEY CLUSTERED ([ID_Notification_Morpheme] ASC)
GO

ALTER TABLE [Notification_Morpheme] 
 ADD CONSTRAINT [UK_Notification_Morpheme_Template] UNIQUE NONCLUSTERED ([Template] ASC)
GO

ALTER TABLE [Notificztion_Task] 
 ADD CONSTRAINT [PK_Notificztion_Template]
	PRIMARY KEY CLUSTERED ([ID_Notificztion_Task] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Notificztion_Task_Notification_Event] 
 ON [Notificztion_Task] ([ID_Notification_Event] ASC)
GO

ALTER TABLE [Phone] 
 ADD CONSTRAINT [PK_Phone]
	PRIMARY KEY CLUSTERED ([ID_Phone] ASC)
GO

ALTER TABLE [Phone] 
 ADD CONSTRAINT [UK_Phone_Phone_Row] UNIQUE NONCLUSTERED ([Phone_Row] ASC)
GO

ALTER TABLE [Product_License] 
 ADD CONSTRAINT [PK_Product_License]
	PRIMARY KEY CLUSTERED ([ID_Product_License] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_License_Client] 
 ON [Product_License] ([ID_Client] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_License_License_Type] 
 ON [Product_License] ([ID_License_Type] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Product_License_Project] 
 ON [Product_License] ([ID_Project] ASC)
GO

ALTER TABLE [Project] 
 ADD CONSTRAINT [PK_Project]
	PRIMARY KEY CLUSTERED ([ID_Project] ASC)
GO

ALTER TABLE [Project] 
 ADD CONSTRAINT [UK_Project_Name] UNIQUE NONCLUSTERED ([Name] ASC)
GO

ALTER TABLE [Project_Access_Function] 
 ADD CONSTRAINT [PK_Project_Access_Function]
	PRIMARY KEY CLUSTERED ([ID_Role_Access_Function] ASC)
GO

ALTER TABLE [Project_Access_Function] 
 ADD CONSTRAINT [UK_Role_Access_Function_Name] UNIQUE NONCLUSTERED ([Name] ASC)
GO

ALTER TABLE [Project_Role] 
 ADD CONSTRAINT [PK_Project_Role]
	PRIMARY KEY CLUSTERED ([ID_Project_Role] ASC)
GO

ALTER TABLE [Project_Role] 
 ADD CONSTRAINT [UK_Project_Role_Name] UNIQUE NONCLUSTERED ([Role_Name] ASC)
GO

ALTER TABLE [Project_Role_Access_Function] 
 ADD CONSTRAINT [PK_Project_Role_Access_Function]
	PRIMARY KEY CLUSTERED ([ID_Role_Access_Function] ASC,[ID_Project_Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Project_Role_Access_Function_Project_Access_Function] 
 ON [Project_Role_Access_Function] ([ID_Role_Access_Function] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Project_Role_Access_Function_Project_Role] 
 ON [Project_Role_Access_Function] ([ID_Project_Role] ASC)
GO

ALTER TABLE [Support_Entitlement] 
 ADD CONSTRAINT [PK_Support_Entitlement]
	PRIMARY KEY CLUSTERED ([ID_Support_Entitlement] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Support_Entitlement_Client] 
 ON [Support_Entitlement] ([ID_Client] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Support_Entitlement_Project] 
 ON [Support_Entitlement] ([ID_Project] ASC)
GO

ALTER TABLE [User] 
 ADD CONSTRAINT [PK_User]
	PRIMARY KEY CLUSTERED ([ID_User] ASC)
GO

ALTER TABLE [User] 
 ADD CONSTRAINT [UK_User_Login] UNIQUE NONCLUSTERED ([Login] ASC)
GO

ALTER TABLE [User] 
 ADD CONSTRAINT [UK_User_E-Mail] UNIQUE NONCLUSTERED ([E-mail] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_User_User_Role] 
 ON [User] ([ID_User] ASC)
GO

ALTER TABLE [User_And_His_Role] 
 ADD CONSTRAINT [PK_User_User_Role]
	PRIMARY KEY CLUSTERED ([ID_User] ASC,[ID_User_Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_And_His_Role_Global_User_Role] 
 ON [User_And_His_Role] ([ID_User_Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_And_His_Role_User] 
 ON [User_And_His_Role] ([ID_User] ASC)
GO

ALTER TABLE [User_Invitation] 
 ADD CONSTRAINT [PK_User_Invitation]
	PRIMARY KEY CLUSTERED ([ID_User_Invitation] ASC)
GO

ALTER TABLE [User_Invitation] 
 ADD CONSTRAINT [UK_E-mail_User_Invitation] UNIQUE NONCLUSTERED ([E-mail] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_Invitation_User] 
 ON [User_Invitation] ([ID_User_Referrer] ASC)
GO

ALTER TABLE [User_Project] 
 ADD CONSTRAINT [PK_User_Project]
	PRIMARY KEY CLUSTERED ([ID_User] ASC,[ID_Project] ASC,[ID_Project_Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_Project_Project] 
 ON [User_Project] ([ID_Project] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_Project_Project_Role] 
 ON [User_Project] ([ID_Project_Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_Project_User] 
 ON [User_Project] ([ID_User] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_Role_Access_Function_Access_Function] 
 ON [User_Role_Access_Function] ([ID_Access_Function] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_User_Role_Access_Function_User_Role] 
 ON [User_Role_Access_Function] ([ID_User_Role] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Client] ADD CONSTRAINT [FK_Client_Client_Type]
	FOREIGN KEY ([ID_Client_Type]) REFERENCES [Client_Type] ([ID_Client_Type]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Client_Address] ADD CONSTRAINT [FK_Client_Address_Address]
	FOREIGN KEY ([ID_Address]) REFERENCES [Address] ([ID_Address]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Client_Address] ADD CONSTRAINT [FK_Client_Address_Client]
	FOREIGN KEY ([ID_Client]) REFERENCES [Client] ([ID_Client]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Client_Email] ADD CONSTRAINT [FK_Client_Email_Client]
	FOREIGN KEY ([ID_Client]) REFERENCES [Client] ([ID_Client]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Client_Email] ADD CONSTRAINT [FK_Client_Email_E-mail]
	FOREIGN KEY ([ID_E-mail]) REFERENCES [E-mail] ([ID_E-mail]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Client_Phone] ADD CONSTRAINT [FK_Client_Phone_Client]
	FOREIGN KEY ([ID_Client]) REFERENCES [Client] ([ID_Client]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Client_Phone] ADD CONSTRAINT [FK_Client_Phone_Phone]
	FOREIGN KEY ([ID_Phone]) REFERENCES [Phone] ([ID_Phone]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [E-mail_Notification] ADD CONSTRAINT [FK_E-mail_Notification_Notificztion_Task]
	FOREIGN KEY ([ID_Notificztion_Task]) REFERENCES [Notificztion_Task] ([ID_Notificztion_Task]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [E-mail_Notification] ADD CONSTRAINT [FK_E-mail_Notification_Project]
	FOREIGN KEY ([ID_Project]) REFERENCES [Project] ([ID_Project]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Notificztion_Task] ADD CONSTRAINT [FK_Notificztion_Task_Notification_Event]
	FOREIGN KEY ([ID_Notification_Event]) REFERENCES [Notification_Event] ([ID_Notification_Event]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Product_License] ADD CONSTRAINT [FK_Product_License_Client]
	FOREIGN KEY ([ID_Client]) REFERENCES [Client] ([ID_Client]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Product_License] ADD CONSTRAINT [FK_Product_License_License_Type]
	FOREIGN KEY ([ID_License_Type]) REFERENCES [License_Type] ([ID_License_Type]) ON DELETE No Action ON UPDATE Cascade
GO

ALTER TABLE [Product_License] ADD CONSTRAINT [FK_Product_License_Project]
	FOREIGN KEY ([ID_Project]) REFERENCES [Project] ([ID_Project]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Project_Role_Access_Function] ADD CONSTRAINT [FK_Project_Role_Access_Function_Project_Access_Function]
	FOREIGN KEY ([ID_Role_Access_Function]) REFERENCES [Project_Access_Function] ([ID_Role_Access_Function]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Project_Role_Access_Function] ADD CONSTRAINT [FK_Project_Role_Access_Function_Project_Role]
	FOREIGN KEY ([ID_Project_Role]) REFERENCES [Project_Role] ([ID_Project_Role]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Support_Entitlement] ADD CONSTRAINT [FK_Support_Entitlement_Client]
	FOREIGN KEY ([ID_Client]) REFERENCES [Client] ([ID_Client]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Support_Entitlement] ADD CONSTRAINT [FK_Support_Entitlement_Project]
	FOREIGN KEY ([ID_Project]) REFERENCES [Project] ([ID_Project]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [User_And_His_Role] ADD CONSTRAINT [FK_User_And_His_Role_Global_User_Role]
	FOREIGN KEY ([ID_User_Role]) REFERENCES [Global_User_Role] ([ID_User_Role]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [User_And_His_Role] ADD CONSTRAINT [FK_User_And_His_Role_User]
	FOREIGN KEY ([ID_User]) REFERENCES [User] ([ID_User]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [User_Invitation] ADD CONSTRAINT [FK_User_Invitation_User]
	FOREIGN KEY ([ID_User_Referrer]) REFERENCES [User] ([ID_User]) ON DELETE No Action ON UPDATE Cascade
GO

ALTER TABLE [User_Project] ADD CONSTRAINT [FK_User_Project_Project]
	FOREIGN KEY ([ID_Project]) REFERENCES [Project] ([ID_Project]) ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE [User_Project] ADD CONSTRAINT [FK_User_Project_Project_Role]
	FOREIGN KEY ([ID_Project_Role]) REFERENCES [Project_Role] ([ID_Project_Role]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [User_Project] ADD CONSTRAINT [FK_User_Project_User]
	FOREIGN KEY ([ID_User]) REFERENCES [User] ([ID_User]) ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE [User_Role_Access_Function] ADD CONSTRAINT [FK_User_Role_Access_Function_Access_Function]
	FOREIGN KEY ([ID_Access_Function]) REFERENCES [Access_Function] ([ID_Access_Function]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [User_Role_Access_Function] ADD CONSTRAINT [FK_User_Role_Access_Function_User_Role]
	FOREIGN KEY ([ID_User_Role]) REFERENCES [Global_User_Role] ([ID_User_Role]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Access_Function', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит функции, к которым может иметь доступ пользователь', 'SCHEMA', 'dbo', 'table', 'Access_Function' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит функции, к которым может иметь доступ пользователь', 'SCHEMA', 'dbo', 'table', 'Access_Function' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Название функции, к которой предоставляется доступ', 'Schema', [dbo], 'table', [Access_Function], 'column', [Function_Name]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Address', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит список адресов', 'SCHEMA', 'dbo', 'table', 'Address' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит список адресов', 'SCHEMA', 'dbo', 'table', 'Address' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Название клиента', 'Schema', [dbo], 'table', [Client], 'column', [Name]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Внутреннее название клиента (между собой)', 'Schema', [dbo], 'table', [Client], 'column', [Inner_Name]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Client_Type', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Тип клиента  	1. Организация 	2. ИП 	3. Физ. лицо', 'SCHEMA', 'dbo', 'table', 'Client_Type' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Тип клиента  	1. Организация 	2. ИП 	3. Физ. лицо', 'SCHEMA', 'dbo', 'table', 'Client_Type' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Название типа клиента', 'Schema', [dbo], 'table', [Client_Type], 'column', [Type_Name]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'E-mail', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Список электронных почтовых ящиков', 'SCHEMA', 'dbo', 'table', 'E-mail' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Список электронных почтовых ящиков', 'SCHEMA', 'dbo', 'table', 'E-mail' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Ажрес почтового ящика', 'Schema', [dbo], 'table', [E-mail], 'column', [Address]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'E-mail_Notification', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит уведомления по проектам', 'SCHEMA', 'dbo', 'table', 'E-mail_Notification' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит уведомления по проектам', 'SCHEMA', 'dbo', 'table', 'E-mail_Notification' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Идентификатор пользователя, для которого будет прилетать оповещение', 'Schema', [dbo], 'table', [E-mail_Notification], 'column', [ID_User_To_Notificate]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Идентификатор проекта, по которому должно прилетать оповещение.', 'Schema', [dbo], 'table', [E-mail_Notification], 'column', [ID_Project]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Global_User_Role', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Роли пользователей в системе  	1. Administrator 	2. User', 'SCHEMA', 'dbo', 'table', 'Global_User_Role' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Роли пользователей в системе  	1. Administrator 	2. User', 'SCHEMA', 'dbo', 'table', 'Global_User_Role' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Название роли', 'Schema', [dbo], 'table', [Global_User_Role], 'column', [Name]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Invitation_User_Settings', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит настройки по приглашённым пользователям.', 'SCHEMA', 'dbo', 'table', 'Invitation_User_Settings' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит настройки по приглашённым пользователям.', 'SCHEMA', 'dbo', 'table', 'Invitation_User_Settings' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Количество приглашений, которые пользователь может отправить за 1 день.', 'Schema', [dbo], 'table', [Invitation_User_Settings], 'column', [Count_Invitations_Per_Day]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Почтовый ящик, с которого будут отправляться приглашения на присоединение', 'Schema', [dbo], 'table', [Invitation_User_Settings], 'column', [Invitation_E-mail]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'LDAP_Settings', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Конфигурация сервера LDAP', 'SCHEMA', 'dbo', 'table', 'LDAP_Settings' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Конфигурация сервера LDAP', 'SCHEMA', 'dbo', 'table', 'LDAP_Settings' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Список domain component', 'Schema', [dbo], 'table', [LDAP_Settings], 'column', [Domain_Components]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Список organizational unit', 'Schema', [dbo], 'table', [LDAP_Settings], 'column', [Organizational_Unit]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'License_Type', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Типы лицензий, которые доступны для продуктов', 'SCHEMA', 'dbo', 'table', 'License_Type' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Типы лицензий, которые доступны для продуктов', 'SCHEMA', 'dbo', 'table', 'License_Type' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Название типа лицензии', 'Schema', [dbo], 'table', [License_Type], 'column', [Type_Name]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Notification_Event', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'События системы, относиельно которых, отправляются оповещения.', 'SCHEMA', 'dbo', 'table', 'Notification_Event' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'События системы, относиельно которых, отправляются оповещения.', 'SCHEMA', 'dbo', 'table', 'Notification_Event' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Тип события - жёстко задан в системе:  	1. Завершение периода ТП по проекту 	2. Завершение лицензии по проекту.', 'Schema', [dbo], 'table', [Notification_Event], 'column', [Event_Type]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Notification_Morpheme', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит список морфем, для создания шаблонов оповещений', 'SCHEMA', 'dbo', 'table', 'Notification_Morpheme' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит список морфем, для создания шаблонов оповещений', 'SCHEMA', 'dbo', 'table', 'Notification_Morpheme' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Сама морфема', 'Schema', [dbo], 'table', [Notification_Morpheme], 'column', [Template]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Описание морфемы', 'Schema', [dbo], 'table', [Notification_Morpheme], 'column', [Description]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Notificztion_Task', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Задача оповещения.', 'SCHEMA', 'dbo', 'table', 'Notificztion_Task' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Задача оповещения.', 'SCHEMA', 'dbo', 'table', 'Notificztion_Task' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Количество месяцев до', 'Schema', [dbo], 'table', [Notificztion_Task], 'column', [Notification_Before_Month]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Текст оповещения, включая различные морфемы параметров.', 'Schema', [dbo], 'table', [Notificztion_Task], 'column', [Notification_Text]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Идентификатор события, относительно которого должно отправляться оповещение', 'Schema', [dbo], 'table', [Notificztion_Task], 'column', [ID_Notification_Event]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Название задачи оповещения', 'Schema', [dbo], 'table', [Notificztion_Task], 'column', [Name]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Phone', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит список телефонов', 'SCHEMA', 'dbo', 'table', 'Phone' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит список телефонов', 'SCHEMA', 'dbo', 'table', 'Phone' 
end


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Product_License', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит список лицензий на продукты, выданные конкрентным компаниям', 'SCHEMA', 'dbo', 'table', 'Product_License' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит список лицензий на продукты, выданные конкрентным компаниям', 'SCHEMA', 'dbo', 'table', 'Product_License' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Проект, на которую выдана лицензия', 'Schema', [dbo], 'table', [Product_License], 'column', [ID_Project]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Клиент, которму выдана лицензия', 'Schema', [dbo], 'table', [Product_License], 'column', [ID_Client]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Дата выдачи лицензии', 'Schema', [dbo], 'table', [Product_License], 'column', [Date_Begin]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Дата окончания лицензии', 'Schema', [dbo], 'table', [Product_License], 'column', [Date_End]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Тип лицензии, которая была передана клиенту', 'Schema', [dbo], 'table', [Product_License], 'column', [ID_License_Type]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Количество выданных лицензий', 'Schema', [dbo], 'table', [Product_License], 'column', [License_Count]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Детали по лицензии, номер договора...', 'Schema', [dbo], 'table', [Product_License], 'column', [Details]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Project', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Проект', 'SCHEMA', 'dbo', 'table', 'Project' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Проект', 'SCHEMA', 'dbo', 'table', 'Project' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Название проекта (по этому полю идёт полнотекстовый поиск).', 'Schema', [dbo], 'table', [Project], 'column', [Name]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Дата создания проекта', 'Schema', [dbo], 'table', [Project], 'column', [Date_Create]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Project_Access_Function', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Список функций, которые погут выполнять пользователи над проектами  	1. AddDelUser 	2. AddDelSupportEntitlement 	3. AddDelClient 	4. ...', 'SCHEMA', 'dbo', 'table', 'Project_Access_Function' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Список функций, которые погут выполнять пользователи над проектами  	1. AddDelUser 	2. AddDelSupportEntitlement 	3. AddDelClient 	4. ...', 'SCHEMA', 'dbo', 'table', 'Project_Access_Function' 
end

EXEC sp_addextendedproperty 'MS_Description', 'ID', 'Schema', [dbo], 'table', [Project_Access_Function], 'column', [ID_Role_Access_Function]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Название функции', 'Schema', [dbo], 'table', [Project_Access_Function], 'column', [Name]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Project_Role', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит список ролей в проекте. По-умолчанию есть преднастроенный список ролей, но для каждого проекта пользователь может эти роли редактировать. Одна роль есть всегда - администратор проекта, обеспечивает полный доступ к проекту.', 'SCHEMA', 'dbo', 'table', 'Project_Role' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит список ролей в проекте. По-умолчанию есть преднастроенный список ролей, но для каждого проекта пользователь может эти роли редактировать. Одна роль есть всегда - администратор проекта, обеспечивает полный доступ к проекту.', 'SCHEMA', 'dbo', 'table', 'Project_Role' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Флаг показывает является ли данная роль администратором. Эта роль создаётся автоматически и не может быть удалена.', 'Schema', [dbo], 'table', [Project_Role], 'column', [Is_Admin]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Project_Role_Access_Function', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит сопоставления между ролями проекта и их функциями в проекте', 'SCHEMA', 'dbo', 'table', 'Project_Role_Access_Function' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит сопоставления между ролями проекта и их функциями в проекте', 'SCHEMA', 'dbo', 'table', 'Project_Role_Access_Function' 
end


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Support_Entitlement', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Право на Тех. поддержку', 'SCHEMA', 'dbo', 'table', 'Support_Entitlement' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Право на Тех. поддержку', 'SCHEMA', 'dbo', 'table', 'Support_Entitlement' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Заметки по работе ТП', 'Schema', [dbo], 'table', [Support_Entitlement], 'column', [Note]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'User', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Пользователь системы', 'SCHEMA', 'dbo', 'table', 'User' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Пользователь системы', 'SCHEMA', 'dbo', 'table', 'User' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Имя пользователя', 'Schema', [dbo], 'table', [User], 'column', [Name]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Хеш пароля пользователя', 'Schema', [dbo], 'table', [User], 'column', [Password]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Является ли пользователь LDAP пользователем', 'Schema', [dbo], 'table', [User], 'column', [Is_Ldap_User]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Почтовый ящик пользователя', 'Schema', [dbo], 'table', [User], 'column', [E-mail]
GO

EXEC sp_addextendedproperty 'MS_Description', 'User login or nickname', 'Schema', [dbo], 'table', [User], 'column', [Login]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'User_And_His_Role', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица содержит сопоставление по ролям пользователей', 'SCHEMA', 'dbo', 'table', 'User_And_His_Role' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица содержит сопоставление по ролям пользователей', 'SCHEMA', 'dbo', 'table', 'User_And_His_Role' 
end


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'User_Invitation', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Список пиглашений разосланных пользователям на электронную почту', 'SCHEMA', 'dbo', 'table', 'User_Invitation' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Список пиглашений разосланных пользователям на электронную почту', 'SCHEMA', 'dbo', 'table', 'User_Invitation' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Дата, когда было отправлено приглашение', 'Schema', [dbo], 'table', [User_Invitation], 'column', [Date_Of_Invitation]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Пользователь, который пригласил.', 'Schema', [dbo], 'table', [User_Invitation], 'column', [ID_User_Referrer]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Принял ли новый пользователь приглашение. Если да, то на указанные e-mail больше нельзя отправить приглашения.', 'Schema', [dbo], 'table', [User_Invitation], 'column', [IsAccepted]
GO


if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'User_Project', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Таблица сопоставления пользователей и проектов', 'SCHEMA', 'dbo', 'table', 'User_Project' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Таблица сопоставления пользователей и проектов', 'SCHEMA', 'dbo', 'table', 'User_Project' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Роль, которая была назначена пользователю в конкретном проекте', 'Schema', [dbo], 'table', [User_Project], 'column', [ID_Project_Role]
GO
