//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonfly.Database.MsSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation_User_Settings
    {
        public decimal ID_Invitation_User_Settings { get; set; }
        public decimal Count_Invitations_Per_Day { get; set; }
        public string Invitation_E_mail { get; set; }
    }
}
