//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonfly.Database.MsSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDAP_Settings
    {
        public decimal ID_LDAP_Settings { get; set; }
        public string Domain_Components { get; set; }
        public byte[] Organizational_Unit { get; set; }
    }
}
