//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonfly.Database.MsSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Morpheme
    {
        public decimal ID_Notification_Morpheme { get; set; }
        public string Template { get; set; }
        public string Description { get; set; }
    }
}
