//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonfly.Database.MsSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Project
    {
        public decimal ID_User { get; set; }
        public decimal ID_Project { get; set; }
        public decimal ID_Project_Role { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Project_Role Project_Role { get; set; }
        public virtual User User { get; set; }
    }
}
